sudo: required
dist: trusty

language:
  - c

matrix:
  include:
    - env: BUILD=DEBUG
      compiler: gcc

    - env: BUILD=RELEASE
      compiler: gcc

    - env: BUILD=DEBUG
      compiler: clang

    - env: BUILD=RELEASE
      compiler: clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc
  - if [ "$CC" == "clang" ]; then sudo apt-get install -qq clang; fi
  - if [ "$CC" == "clang" ]; then export CC="clang"; fi
  - export CMAKEV=3.8.1
  - wget https://cmake.org/files/v3.8/cmake-$CMAKEV.tar.gz
  - tar xf cmake-$CMAKEV.tar.gz
  - cd cmake-$CMAKEV
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - $CC --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DBuildBench=OFF
  - make
  - ./test/xs_tests
